    
CREATE TABLE IF NOT EXISTS users(
    id  INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash  CHAR(60) NOT NULL,
    created_at DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS vault_items(
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    titulo VARCHAR(100) NOT NULL, 
    `url` VARCHAR(100)  NULL,
    `login` VARCHAR(100)  NULL,
    senha_cifrada VARCHAR(1024) NOT NULL,
    categoria VARCHAR(100) NOT NULL,
    iv CHAR(16) NOT NULL,
    auth_tag CHAR(24) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_id FOREIGN KEY  (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    INDEX (user_id)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



